version: '3'

name: gobank

volumes:
  postgresdata: {}

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
      
  postgres:
    image: "docker.io/postgres:16-alpine"
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
    - postgres:/home/postgres/pgdata/data
