version: '3'

name: go-api

volumes:
  postgres: 

services:
  postgres:
    image: "docker.io/postgres:16-alpine"
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
    - postgres:/home/postgres/pgdata/data

  app:
    build:
      context: .
    environment:
      APP_PORT: 8080
      DB_HOST: localhost
      DB_USER: app
      DB_PASS: app
      DB_NAME: app
      DB_PORT: 5432
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
    links:
      - postgres
      
